default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  username: root
  password:
  host: localhost
  database: fitit

test:
  <<: *default
  database: fitit_test

# DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  host: redpineapple.cdndxqoeul8v.us-west-2.rds.amazonaws.com
  username: janevern
  password: helloworld123
  database: fitit_prod
  port: 3306
  #port: 3303
  #host: avetty-production.cdndxqoeul8v.us-west-2.rds.amazonaws.com