default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development:
  <<: *default
  database: fitit

test:
  <<: *default
  database: fitit_test

# DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
production:
  <<: *default
  host: mysql-tryitontoday.cuxn4i8bynjf.us-east-1.rds.amazonaws.com
  database: fitit
  username: janevern
  password: ilmhPVvm1
  port: 3306
  #port: 3303
  #host: avetty-production.cdndxqoeul8v.us-west-2.rds.amazonaws.com